version: '2'
.catalog:
  name: "Open Web"
  version: 7.0.0
  description: |
    Open Web version 7
  questions:
    - variable: "site_name"
      type: string
      required: true
      label: "Nom du site"
      description: "Nom unique du site Open Web"
services:
  nginx:
    scale: 1
    start_on_create: true
  php:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true