version: '2'
services:
  openweb-data:
    image: registry.srvopenwebrancher.local:5000/ow-php
    volumes:
      - /var/www/html/openweb-repo/web
    labels:
      io.rancher.container.start_once: true
  php:
    image: registry.srvopenwebrancher.local:5000/ow-php
    environment:
      ow_db_server: database
      ow_db_name: openweb_${site_name}
      ow_db_user: ${site_name}
      ow_db_password: ${site_name}
      ow_elasticsearch_index: openweb_${site_name}
      ow_elasticsearch_servers: elastic
    stdin_open: true
    external_links:
    - galera/galera-lb:database
    volumes_from:
    - openweb-data
    tty: true
    links:
    - redis:redis
    labels:
      io.rancher.sidekicks: openweb-data
      io.rancher.container.pull_image: always
  redis:
    image: redis:3
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  nginx:
    image: registry.srvopenwebrancher.local:5000/ow-nginx
    stdin_open: true
    volumes_from:
    - openweb-data
    tty: true
    links:
    - php:php
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft: io.rancher.stack.name=$${stack_name}