version: '2'
services:
  nginx:
    image: registry.srvopenwebrancher.local:5000/ow-nginx
    stdin_open: true
    volumes_from:
    - php
    tty: true
    links:
    - php:php
    labels:
      io.rancher.container.pull_image: always
  php:
    image: registry.srvopenwebrancher.local:5000/ow-php
    environment:
      ow_db_server: database
      ow_db_name: openweb_${site_name}
      ow_db_user: ${site_name}
      ow_db_password: ${site_name}
      ow_elasticsearch_index: openweb_${site_name}
      ow_elasticsearch_servers: elastic
    stdin_open: true
    external_links:
    - galera/galera-lb:database
    volumes:
    - /mnt/APACHE_COMMON_FILES/openweb/${site_name}/ressources:/var/www/html/openweb-repo/web/ressources
    - /mnt/APACHE_COMMON_FILES/openweb/${site_name}/themes:/var/www/html/openweb-repo/web/themes
    tty: true
    links:
    - redis:redis
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:3
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
